//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IshirakuCooker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int ИдЗаказа { get; set; }
        public int ИдБлюда { get; set; }
        public System.TimeSpan ВремяЗаказа { get; set; }
        public int ИдСотрудника { get; set; }
        public string ОбщееКоличество { get; set; }
        public int СтатусЗаказа { get; set; }
    
        public virtual Блюда Блюда { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual СтатусЗаказа СтатусЗаказа1 { get; set; }
    }
}
